insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (1, 'Dept 1', 'Canha');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (2, 'Dept 2', 'Picton');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (3, 'Dept 3', 'Huainan');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (4, 'Dept 4', 'Nowe Skalmierzyce');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (5, 'Dept 5', 'Boksitogorsk');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (6, 'Dept 6', 'Nanyang');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (7, 'Dept 7', 'Jaciara');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (8, 'Dept 8', 'Aachen');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (9, 'Dept 9', 'Sydney');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (10, 'Dept 10', 'Ciduren');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (11, 'Dept 11', 'Kalashnikovo');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (12, 'Dept 12', 'Mochishche');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (13, 'Dept 13', 'Qingxi');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (14, 'Dept 14', 'Guacamaya');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (15, 'Dept 15', 'Cunha');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (16, 'Dept 16', 'Pervomaysk');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (17, 'Dept 17', 'Rakek');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (18, 'Dept 18', 'Mbuji-Mayi');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (19, 'Dept 19', 'Affery');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (20, 'Dept 20', 'Panyindangan');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (21, 'Dept 21', 'Xinzhan');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (22, 'Dept 22', 'Spodnja Hajdina');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (23, 'Dept 23', 'Itami');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (24, 'Dept 24', 'Dasha');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (25, 'Dept 25', 'Timurjaya');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (26, 'Dept 26', 'Pengshi');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (27, 'Dept 27', 'Lagangilang');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (28, 'Dept 28', 'Kozhevnikovo');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (29, 'Dept 29', 'Solsona');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (30, 'Dept 30', 'Mszana Dolna');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (31, 'Dept 31', 'Harstad');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (32, 'Dept 32', 'Bailingnao');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (33, 'Dept 33', 'Oygon');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (34, 'Dept 34', 'Fada N''gourma');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (35, 'Dept 35', 'Honghualiangzi');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (36, 'Dept 36', 'Telsiai');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (37, 'Dept 37', 'Starokorsunskaya');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (38, 'Dept 38', 'Changchuan');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (39, 'Dept 39', 'Kingston');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (40, 'Dept 40', 'Saint-Lô');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (41, 'Dept 41', 'Södertälje');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (42, 'Dept 42', 'Sémbé');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (43, 'Dept 43', 'Paris 07');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (44, 'Dept 44', 'Shibirghān');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (45, 'Dept 45', 'Ouadda');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (46, 'Dept 46', 'Zdenci');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (47, 'Dept 47', 'Mississauga');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (48, 'Dept 48', 'Būr Safājah');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (49, 'Dept 49', 'Kumagunnam');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (50, 'Dept 50', 'Paris 14');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (51, 'Dept 51', 'Greda');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (52, 'Dept 52', 'Limoges');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (53, 'Dept 53', 'Bahía de Caráquez');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (54, 'Dept 54', 'Singgugu');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (55, 'Dept 55', 'Kinalansan');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (56, 'Dept 56', 'Ilmajoki');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (57, 'Dept 57', 'Pasvalys');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (58, 'Dept 58', 'Khoronk’');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (59, 'Dept 59', 'Sandefjord');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (60, 'Dept 60', 'Yinghua');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (61, 'Dept 61', 'Elias Fausto');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (62, 'Dept 62', 'Qimantage');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (63, 'Dept 63', 'Tirhanimîne');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (64, 'Dept 64', 'Partizan');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (65, 'Dept 65', 'Krasnogorskiy');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (66, 'Dept 66', 'Vacov');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (67, 'Dept 67', 'Kalenderovci Donji');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (68, 'Dept 68', 'Tangtu');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (69, 'Dept 69', 'Vale de Madeiros');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (70, 'Dept 70', 'Tokonou');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (71, 'Dept 71', 'Dacheng');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (72, 'Dept 72', 'Rancagua');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (73, 'Dept 73', 'Macaíba');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (74, 'Dept 74', 'Limbuš');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (75, 'Dept 75', 'Tarouca');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (76, 'Dept 76', 'Beranci');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (77, 'Dept 77', 'Karlstad');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (78, 'Dept 78', 'Dalsjöfors');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (79, 'Dept 79', 'Umeå');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (80, 'Dept 80', 'Potok Złoty');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (81, 'Dept 81', 'Wan’an');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (82, 'Dept 82', 'Osoyoos');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (83, 'Dept 83', 'Vitina');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (84, 'Dept 84', 'Gayle');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (85, 'Dept 85', 'Makiv');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (86, 'Dept 86', 'Pointe-à-Pitre');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (87, 'Dept 87', 'Poputnaya');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (88, 'Dept 88', 'Villeneuve-la-Garenne');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (89, 'Dept 89', 'Volot');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (90, 'Dept 90', 'Moñitos');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (91, 'Dept 91', 'Energetik');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (92, 'Dept 92', 'Itzer');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (93, 'Dept 93', 'Tongzi');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (94, 'Dept 94', 'Zouiat ech Cheïkh');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (95, 'Dept 95', 'Daliuhang');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (96, 'Dept 96', 'Kaset Sombun');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (97, 'Dept 97', 'Villa Consuelo');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (98, 'Dept 98', 'Uchkulan');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (99, 'Dept 99', 'Mori');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (100, 'Dept 100', 'San Lorenzo');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (101, 'Dept 101', 'Bernardo de Irigoyen');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (102, 'Dept 102', 'Vyškov');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (103, 'Dept 103', 'Hanamaki');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (104, 'Dept 104', 'Södertälje');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (105, 'Dept 105', 'Kitango');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (106, 'Dept 106', 'Poyang');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (107, 'Dept 107', 'Huangsha');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (108, 'Dept 108', 'New York City');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (109, 'Dept 109', 'Olszówka');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (110, 'Dept 110', 'Santa Cruz');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (111, 'Dept 111', 'Odintsovo');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (112, 'Dept 112', 'Nizhniy Bestyakh');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (113, 'Dept 113', 'Facatativá');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (114, 'Dept 114', 'Halmstad');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (115, 'Dept 115', 'Masaki-chō');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (116, 'Dept 116', 'Nanterre');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (117, 'Dept 117', 'Paobulan');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (118, 'Dept 118', 'Pedregulho');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (119, 'Dept 119', 'Koesan');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (120, 'Dept 120', 'Kiiminki');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (121, 'Dept 121', 'Orangeville');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (122, 'Dept 122', 'Emmaboda');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (123, 'Dept 123', 'Pushkino');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (124, 'Dept 124', 'Mykonos');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (125, 'Dept 125', 'Kuroishi');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (126, 'Dept 126', 'Majiao');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (127, 'Dept 127', 'Suita');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (128, 'Dept 128', 'Sa Kaeo');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (129, 'Dept 129', 'Chenārān');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (130, 'Dept 130', 'Mineralni Bani');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (131, 'Dept 131', 'Citasuk');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (132, 'Dept 132', 'Mezinovskiy');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (133, 'Dept 133', 'Chenda');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (134, 'Dept 134', 'Ševica');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (135, 'Dept 135', 'Sukkozero');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (136, 'Dept 136', 'Pomacocha');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (137, 'Dept 137', '‘Awaj');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (138, 'Dept 138', 'Modis');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (139, 'Dept 139', 'Toktogul');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (140, 'Dept 140', 'Sakété');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (141, 'Dept 141', 'Guaíba');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (142, 'Dept 142', 'Castellon De La Plana/Castello De La Pla');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (143, 'Dept 143', 'Loa Janan');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (144, 'Dept 144', 'Talangnan');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (145, 'Dept 145', 'Caihe');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (146, 'Dept 146', 'Dongyang');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (147, 'Dept 147', 'Kujung');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (148, 'Dept 148', 'Cambuga');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (149, 'Dept 149', 'Hoani');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (150, 'Dept 150', 'Tapakrejo');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (151, 'Dept 151', 'Pepe');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (152, 'Dept 152', 'Gamovo');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (153, 'Dept 153', 'Cabcaben');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (154, 'Dept 154', 'Taihua');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (155, 'Dept 155', 'Yangwei');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (156, 'Dept 156', 'Kiihtelysvaara');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (157, 'Dept 157', 'Tunis');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (158, 'Dept 158', 'Atlanta');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (159, 'Dept 159', 'Mahendranagar');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (160, 'Dept 160', 'Flic en Flac');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (161, 'Dept 161', 'Angochi');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (162, 'Dept 162', 'Bantiran');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (163, 'Dept 163', 'Pansoy');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (164, 'Dept 164', 'Pontevedra');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (165, 'Dept 165', 'Manyava');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (166, 'Dept 166', 'Pancur');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (167, 'Dept 167', 'Nice');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (168, 'Dept 168', 'Genève');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (169, 'Dept 169', 'Bodzentyn');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (170, 'Dept 170', 'La Cruz');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (171, 'Dept 171', 'Beitai');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (172, 'Dept 172', 'Wanquan');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (173, 'Dept 173', 'Hōjō');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (174, 'Dept 174', 'Tlogowungu');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (175, 'Dept 175', 'Lilongwe');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (176, 'Dept 176', 'Inhambane');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (177, 'Dept 177', 'Longquan');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (178, 'Dept 178', 'Zhuting');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (179, 'Dept 179', 'Oripää');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (180, 'Dept 180', 'Tanjung');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (181, 'Dept 181', 'Kashirskoye');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (182, 'Dept 182', 'Shatoujiao');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (183, 'Dept 183', 'Pathum Rat');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (184, 'Dept 184', 'Necoclí');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (185, 'Dept 185', '''Ali Sabieh');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (186, 'Dept 186', 'Saparbay');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (187, 'Dept 187', 'Ţāmiyah');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (188, 'Dept 188', 'Carrizal');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (189, 'Dept 189', 'Pemzashen');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (190, 'Dept 190', 'Vinež');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (191, 'Dept 191', 'Huxiaoqiao');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (192, 'Dept 192', 'Treinta y Tres');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (193, 'Dept 193', 'Waterloo');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (194, 'Dept 194', 'Gandusari');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (195, 'Dept 195', 'Muruni');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (196, 'Dept 196', 'Zafar');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (197, 'Dept 197', 'Gaula');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (198, 'Dept 198', 'Xinxu');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (199, 'Dept 199', 'Haoba');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (200, 'Dept 200', 'Jesús Menéndez');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (201, 'Dept 201', 'Saint George''s');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (202, 'Dept 202', 'Hejiaping');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (203, 'Dept 203', 'Xinji');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (204, 'Dept 204', 'Grenoble');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (205, 'Dept 205', 'Pasadena');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (206, 'Dept 206', 'Leon Postigo');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (207, 'Dept 207', 'Zaysan');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (208, 'Dept 208', 'Palmas Bellas');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (209, 'Dept 209', 'Basīrpur');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (210, 'Dept 210', 'Sal’sk');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (211, 'Dept 211', 'Melun');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (212, 'Dept 212', 'Wuppertal');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (213, 'Dept 213', 'Namasuba');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (214, 'Dept 214', 'Krebet');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (215, 'Dept 215', 'Licheng');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (216, 'Dept 216', 'Oinófyta');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (217, 'Dept 217', 'São João Nepomuceno');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (218, 'Dept 218', 'Thị Trấn Ngọc Lặc');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (219, 'Dept 219', 'Ryazhsk');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (220, 'Dept 220', 'Detroit');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (221, 'Dept 221', 'Tiassalé');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (222, 'Dept 222', 'Korenëvo');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (223, 'Dept 223', 'Kungsbacka');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (224, 'Dept 224', 'Baleber');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (225, 'Dept 225', 'Novokhovrino');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (226, 'Dept 226', 'Ar Riqāmā');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (227, 'Dept 227', 'Thala');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (228, 'Dept 228', 'Gengcheng');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (229, 'Dept 229', 'Miętne');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (230, 'Dept 230', 'Replot');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (231, 'Dept 231', 'Veselynove');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (232, 'Dept 232', 'Voskehask');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (233, 'Dept 233', 'Boleiros');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (234, 'Dept 234', 'Maoyang');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (235, 'Dept 235', 'Examília');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (236, 'Dept 236', 'Novyy Svit');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (237, 'Dept 237', 'Stockholm');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (238, 'Dept 238', 'Ninh Giang');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (239, 'Dept 239', 'Norsborg');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (240, 'Dept 240', 'Zangbi');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (241, 'Dept 241', 'Washington');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (242, 'Dept 242', 'Estância');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (243, 'Dept 243', 'Gotovlje');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (244, 'Dept 244', 'La Victoria');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (245, 'Dept 245', 'Águas');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (246, 'Dept 246', 'Yiqi');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (247, 'Dept 247', 'Donja Brela');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (248, 'Dept 248', 'Dongfanghong');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (249, 'Dept 249', 'Tver');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (250, 'Dept 250', 'Borovany');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (251, 'Dept 251', 'Belyy Gorodok');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (252, 'Dept 252', 'Saintes');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (253, 'Dept 253', 'Liujiage');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (254, 'Dept 254', 'Kupu');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (255, 'Dept 255', 'Asan-Maina Village');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (256, 'Dept 256', 'La Quiaca');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (257, 'Dept 257', 'Santana');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (258, 'Dept 258', 'Hema');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (259, 'Dept 259', 'Duut');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (260, 'Dept 260', 'Ait Ali');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (261, 'Dept 261', 'Francisco I Madero');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (262, 'Dept 262', 'Bački Breg');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (263, 'Dept 263', 'Leteki');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (264, 'Dept 264', 'Baqiu');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (265, 'Dept 265', 'Farasān');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (266, 'Dept 266', 'Lorient');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (267, 'Dept 267', 'Maurisu');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (268, 'Dept 268', 'Xinpu');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (269, 'Dept 269', 'Västra Frölunda');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (270, 'Dept 270', 'Pavlivka');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (271, 'Dept 271', 'Jeminay');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (272, 'Dept 272', 'Houbai');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (273, 'Dept 273', 'Banjar Teguan');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (274, 'Dept 274', 'Schieren');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (275, 'Dept 275', 'Fontenay-sous-Bois');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (276, 'Dept 276', 'Pathein');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (277, 'Dept 277', 'Pacobamba');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (278, 'Dept 278', 'Vilhelmina');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (279, 'Dept 279', 'Ibitinga');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (280, 'Dept 280', 'Askersund');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (281, 'Dept 281', 'Bahía Blanca');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (282, 'Dept 282', 'Barra dos Coqueiros');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (283, 'Dept 283', 'Brest');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (284, 'Dept 284', 'Suchań');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (285, 'Dept 285', 'Gwandu');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (286, 'Dept 286', 'Esquina');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (287, 'Dept 287', 'Petaling Jaya');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (288, 'Dept 288', 'Kragujevac');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (289, 'Dept 289', 'Winneba');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (290, 'Dept 290', 'Morinville');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (291, 'Dept 291', 'Misheronskiy');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (292, 'Dept 292', 'Rozwadza');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (293, 'Dept 293', 'Valencia');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (294, 'Dept 294', 'Lopatinskiy');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (295, 'Dept 295', 'Santa Luzia');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (296, 'Dept 296', 'Rutul');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (297, 'Dept 297', 'Kramators’k');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (298, 'Dept 298', 'Łyse');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (299, 'Dept 299', 'Bratislava');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (300, 'Dept 300', 'Mayahi');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (301, 'Dept 301', 'Svetlograd');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (302, 'Dept 302', 'Ubatã');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (303, 'Dept 303', 'Qal‘eh-ye Khvājeh');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (304, 'Dept 304', 'Narawayong');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (305, 'Dept 305', 'Wanlongshan');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (306, 'Dept 306', 'Manay');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (307, 'Dept 307', 'Fangqiang');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (308, 'Dept 308', 'Quanzhou');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (309, 'Dept 309', 'Palmas');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (310, 'Dept 310', 'Phlapphla Chai');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (311, 'Dept 311', 'Emiliano Zapata');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (312, 'Dept 312', 'Heicheng');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (313, 'Dept 313', 'Gaocheng');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (314, 'Dept 314', 'Khodasy');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (315, 'Dept 315', 'Rosh Pinna');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (316, 'Dept 316', 'Fatuulan');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (317, 'Dept 317', 'Wasquehal');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (318, 'Dept 318', 'Solok Timur');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (319, 'Dept 319', 'Tonj');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (320, 'Dept 320', 'Lazaro Cardenas');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (321, 'Dept 321', 'Barrie');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (322, 'Dept 322', 'Hule');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (323, 'Dept 323', 'Hengli');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (324, 'Dept 324', 'Keleng');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (325, 'Dept 325', 'Stuttgart');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (326, 'Dept 326', 'Nice');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (327, 'Dept 327', 'Jardinópolis');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (328, 'Dept 328', 'Palopat');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (329, 'Dept 329', 'Gōtsuchō');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (330, 'Dept 330', 'Qiancheng');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (331, 'Dept 331', 'Gojō');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (332, 'Dept 332', 'Zhangxiang');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (333, 'Dept 333', 'Gabrovo');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (334, 'Dept 334', 'Ranao');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (335, 'Dept 335', 'Kuala Lumpur');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (336, 'Dept 336', 'Rio Claro');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (337, 'Dept 337', 'Norberg');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (338, 'Dept 338', 'Sindon');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (339, 'Dept 339', 'Salt Lake City');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (340, 'Dept 340', 'Kol’chugino');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (341, 'Dept 341', 'Ratnapura');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (342, 'Dept 342', 'Artesianón');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (343, 'Dept 343', 'Sanjō');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (344, 'Dept 344', 'Kertorejo');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (345, 'Dept 345', 'Laocheng');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (346, 'Dept 346', 'Tekikbanyuurip');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (347, 'Dept 347', 'Kalávryta');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (348, 'Dept 348', 'Rogachëvo');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (349, 'Dept 349', 'Lishu');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (350, 'Dept 350', 'Razgrad');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (351, 'Dept 351', 'Palma De Mallorca');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (352, 'Dept 352', 'Kallithéa');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (353, 'Dept 353', 'Solidaridad');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (354, 'Dept 354', 'Gremyachinsk');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (355, 'Dept 355', 'Governor’s Harbour');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (356, 'Dept 356', 'Shigu');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (357, 'Dept 357', 'Talin Hiag');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (358, 'Dept 358', 'Sattahip');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (359, 'Dept 359', 'Visby');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (360, 'Dept 360', 'Shangyi');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (361, 'Dept 361', 'Dalongdong');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (362, 'Dept 362', 'Rantaupanjang');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (363, 'Dept 363', 'Zlín');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (364, 'Dept 364', 'Kortkeros');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (365, 'Dept 365', 'Mingshui');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (366, 'Dept 366', 'Tayug');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (367, 'Dept 367', 'Trondheim');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (368, 'Dept 368', 'Llusco');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (369, 'Dept 369', 'Yangcun');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (370, 'Dept 370', 'Al Khafjī');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (371, 'Dept 371', 'Kusak');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (372, 'Dept 372', 'Baborów');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (373, 'Dept 373', 'Frisange');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (374, 'Dept 374', 'Jiuzihe');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (375, 'Dept 375', 'Hebei');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (376, 'Dept 376', 'Kalix');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (377, 'Dept 377', 'Yajiang');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (378, 'Dept 378', 'Jiangbu');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (379, 'Dept 379', 'Trần Văn Thời');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (380, 'Dept 380', 'San Pedro de Ycuamandiyú');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (381, 'Dept 381', 'Xia Dawo');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (382, 'Dept 382', 'Carvalho');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (383, 'Dept 383', 'El Paso');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (384, 'Dept 384', 'Chenghuang');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (385, 'Dept 385', 'Paris La Défense');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (386, 'Dept 386', 'Xiaheqing');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (387, 'Dept 387', 'Xinfeng');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (388, 'Dept 388', 'Пласница');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (389, 'Dept 389', 'Bobrowice');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (390, 'Dept 390', 'Sapiranga');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (391, 'Dept 391', 'Geldrop');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (392, 'Dept 392', 'Ujmisht');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (393, 'Dept 393', 'Pyapon');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (394, 'Dept 394', 'Bartolomé Masó');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (395, 'Dept 395', 'Fengkou');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (396, 'Dept 396', 'Tonglin');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (397, 'Dept 397', 'Starychi');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (398, 'Dept 398', 'Pontarlier');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (399, 'Dept 399', 'Duzhenwan');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (400, 'Dept 400', 'Harar');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (401, 'Dept 401', 'Witkowo');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (402, 'Dept 402', 'Pierzchnica');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (403, 'Dept 403', 'Conceição da Barra');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (404, 'Dept 404', 'Kristiansand S');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (405, 'Dept 405', 'Walakeri');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (406, 'Dept 406', 'Alta Gracia');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (407, 'Dept 407', 'Rungis');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (408, 'Dept 408', 'Bourges');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (409, 'Dept 409', 'Niort');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (410, 'Dept 410', 'Quchi');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (411, 'Dept 411', 'Akkol’');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (412, 'Dept 412', 'Amiens');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (413, 'Dept 413', 'Đạ Tẻh');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (414, 'Dept 414', 'Rovira');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (415, 'Dept 415', 'Ban Phaeo');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (416, 'Dept 416', 'Ramos');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (417, 'Dept 417', 'Miskindzha');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (418, 'Dept 418', 'Martingança-Gare');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (419, 'Dept 419', 'Rubik');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (420, 'Dept 420', 'Sukomulyo');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (421, 'Dept 421', 'Pocpo');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (422, 'Dept 422', 'Kuznechikha');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (423, 'Dept 423', 'Yŏnggwang-ŭp');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (424, 'Dept 424', 'Wenci');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (425, 'Dept 425', 'Palermo');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (426, 'Dept 426', 'Sampués');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (427, 'Dept 427', 'Awar-awar');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (428, 'Dept 428', 'Boulder');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (429, 'Dept 429', 'Saeul');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (430, 'Dept 430', 'Kilingi-Nõmme');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (431, 'Dept 431', 'Floresta');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (432, 'Dept 432', 'Mjölby');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (433, 'Dept 433', 'Sandakan');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (434, 'Dept 434', 'Diamante');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (435, 'Dept 435', 'Riyadh');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (436, 'Dept 436', 'Chenghuang');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (437, 'Dept 437', 'Chinchero');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (438, 'Dept 438', 'Huashixia');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (439, 'Dept 439', 'Lukou');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (440, 'Dept 440', 'Lishu');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (441, 'Dept 441', 'Caoping');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (442, 'Dept 442', 'Burgos');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (443, 'Dept 443', 'Jianjun');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (444, 'Dept 444', 'Hejia');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (445, 'Dept 445', 'Tukbur');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (446, 'Dept 446', 'Yisa');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (447, 'Dept 447', 'Jiuzhen');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (448, 'Dept 448', 'Jajawai');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (449, 'Dept 449', 'Muzi');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (450, 'Dept 450', 'Compiègne');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (451, 'Dept 451', 'Shanguang');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (452, 'Dept 452', 'Pedamaran');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (453, 'Dept 453', 'Rzyki');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (454, 'Dept 454', 'Plataran');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (455, 'Dept 455', 'Zhuxi Chengguanzhen');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (456, 'Dept 456', 'Mengdong');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (457, 'Dept 457', 'Bang Bo');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (458, 'Dept 458', 'Haixing');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (459, 'Dept 459', 'Gangsha');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (460, 'Dept 460', 'Wonotirto');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (461, 'Dept 461', 'Gotovlje');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (462, 'Dept 462', 'Ruy Barbosa');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (463, 'Dept 463', 'Hebu');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (464, 'Dept 464', 'Sapporo');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (465, 'Dept 465', 'Langob');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (466, 'Dept 466', 'Lom Sak');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (467, 'Dept 467', 'Klobuky');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (468, 'Dept 468', 'Victoria');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (469, 'Dept 469', 'Saiki');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (470, 'Dept 470', 'La Ensenada');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (471, 'Dept 471', 'Raychikhinsk');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (472, 'Dept 472', 'Talin Hiag');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (473, 'Dept 473', 'Xiaoyi');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (474, 'Dept 474', 'Palaiseau');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (475, 'Dept 475', 'Tanggeung Kolot');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (476, 'Dept 476', 'Ningmute');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (477, 'Dept 477', 'Curahnongko');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (478, 'Dept 478', 'Taloko');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (479, 'Dept 479', 'Don Matías');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (480, 'Dept 480', 'Sidayu');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (481, 'Dept 481', 'Banghai');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (482, 'Dept 482', 'Harrison Brook');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (483, 'Dept 483', 'Paccha');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (484, 'Dept 484', 'Septfontaines');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (485, 'Dept 485', 'Hobo');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (486, 'Dept 486', 'Krajan Jabungcandi');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (487, 'Dept 487', 'Le Pontet');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (488, 'Dept 488', 'Alfenas');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (489, 'Dept 489', 'Blumenau');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (490, 'Dept 490', 'Sayansk');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (491, 'Dept 491', 'Shuidong');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (492, 'Dept 492', 'Sergokala');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (493, 'Dept 493', 'Sibaté');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (494, 'Dept 494', 'Namyang-dong');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (495, 'Dept 495', 'Nakhon Pathom');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (496, 'Dept 496', 'Barayong');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (497, 'Dept 497', 'Porta');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (498, 'Dept 498', 'Kafir Qala');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (499, 'Dept 499', 'Armação de Búzios');
insert into DEPARTMENT (Department_ID, Dept_Name, Location) values (500, 'Dept 500', 'Chibombo');
