DROP TABLE IF EXISTS SHIFT_ASSIGNMENT;
DROP TABLE IF EXISTS OFFICE;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS SHIFT;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS EMPLOYEE_CONTRACT;
DROP TABLE IF EXISTS DEPARTMENT;