SELECT * FROM DEPARTMENT;
SELECT * FROM ROLE;
SELECT * FROM EMPLOYEE;
SELECT * FROM EMPLOYEE_CONTRACT;
SELECT * FROM OFFICE;
SELECT * FROM SHIFT;
SELECT * FROM SHIFT_ASSIGNMENT;

-- בדיקת כמויות
SELECT 'Employees' as table, COUNT(*) FROM EMPLOYEE
UNION ALL
SELECT 'Contracts', COUNT(*) FROM EMPLOYEE_CONTRACT
UNION ALL
SELECT 'Assignments', COUNT(*) FROM SHIFT_ASSIGNMENT;